### ISSUE TITLE
BIDE algorithm returns extra patterns in the result. 

### ISSUE THREAD

**Issue by mdsharifulhaque** [chuanconggao/PrefixSpan-py#14] opened 2019-03-15 14:54 UTC
db = ['c', 'a', 'a', 'b', 'c'], ['a', 'b', 'c', 'b'], ['c', 'a', 'b', 'c'],['a', 'b', 'b', 'c', 'a']
ps.frequent(2, closed=True)

shows result:
[(3, ['c', 'a']), (2, ['c', 'a', 'b', 'c']), (3, ['c', 'b']), (4, ['a']), (2, ['a', 'a']), (4, ['a', 'b']), (4, ['a', 'b', 'c']), (2, ['a', 'b', 'b'])]

which was supposed to be:
[(3, ['c', 'a']), (2, ['c', 'a', 'b', 'c']), (3, ['c', 'b']), (2, ['a', 'a']), (4, ['a', 'b', 'c']), (2, ['a', 'b', 'b'])]

The input is from original paper of [BIDE](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.6.2704&rep=rep1&type=pdf).

**Comment by chuanconggao** [comment] 2019-03-16 03:43
Thank you very much for the feedback. I will fix it ASAP.

**Comment by CharlesGaydon** [comment] 2019-10-04 10:45
Hello!
Has this issue been corrected already?

**Comment by VBota1** [comment] 2020-03-15 23:11
> Hello!
> Has this issue been corrected already?

The Issue is still present.

**Comment by TimHe95** [comment] 2020-04-18 14:46
Still present +1

**Comment by chuanconggao** [comment] 2020-04-19 06:15
Found issue as it was missing a condtion check regarding candidate items of same frequency after current pattern prefix. Will fix soon. 

Sorry for the delay as my schedule was fully packed.

**Comment by chuanconggao** [comment] 2020-06-05 05:43
Fixed now. Tested on provided input example. Thanks for patience.

**Closed by chuanconggao** 2020-06-05 05:43 UTC
Labels: bug
