### ISSUE TITLE
Specify occurrence of each sequence in input

### ISSUE THREAD

**Issue by nltran** [chuanconggao/PrefixSpan-py#17] opened 2019-04-09 09:20 UTC
Hello,

Could the library support occurrence information of sequences in the input? I have data in this form, where the last element of a sequence indicates the number of times this sequence has occurred in the dataset.

c d e 7
b b b d e 89
c c c a 123
b b c c 789

**Comment by chuanconggao** [comment] 2020-06-05 06:24
Seems duplicate of #21. Please double check that one.

**Closed by chuanconggao** 2020-06-05 06:24 UTC
